## Import Data Source

In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
# data = "/Users/ruzlim/Code/Jupyter//Raw_Agg_Performance.csv"
# data = "c/Users/Narut4/coding/Jupyter/Raw_Agg_Performance.csv"
data = "Raw_Agg_Performance.csv"

df = pd.read_csv(data)
df.head()

,TM_KEY_MTH,TM_KEY_WK,CENTER,METRIC_GRP,COMP_CD,PRODUCT_GRP,METRIC_CD,METRIC_NAME,DIMENSION_KPI_FLAG,BG_FLAG,AGG_TYPE,RR_IND,GRY_IND,UOM,PERIOD,ACTUAL_AGG,TARGET_AGG,PPN_TM
0,202303,2023009,Customer Service Experience & Retention,Experience,DTAC,All Services,DSER02401,Abandoned Call Rate : DTAC,N,N,N,0,RYG,%,M,NaN,NaN,2023-05-22 17:50:18
1,202303,2023009,Customer Service Experience & Retention,Experience,DTAC,All Services,DSER02402,Handled Call Rate : DTAC,N,N,N,0,GYR,%,M,NaN,NaN,2023-05-22 17:50:18
2,202303,2023009,Customer Service Experience & Retention,Experience,DTAC,All Services,DSER02501,Call Center CSAT IVR (Top2Boxes) : DTAC,N,N,N,0,GYR,%,M,NaN,NaN,2023-05-22 17:50:18
3,202303,2023009,Customer Service Experience & Retention,Experience,DTAC,Postpaid,DSER21101,Postpaid Complaint : DTAC,Y,N,N,0,RYG,%,M,NaN,NaN,2023-05-22 17:50:18
4,202303,2023009,Customer Service Experience & Retention,Experience,DTAC,Prepaid,DSER22101,Prepaid Complaint : DTAC,Y,N,N,0,RYG,%,M,NaN,NaN,2023-05-22 17:50:18

## Analyze Data

In [ ]:
df.describe()

In [ ]:
df.shape

In [ ]:
df.dtypes

In [ ]:
df.mean(numeric_only=True)

In [ ]:
# Check null value in each column

df.apply(lambda x: sum(x.isnull()), axis=0)

In [ ]:
# Fullfill null value example

df_tmp = df

df_tmp['TARGET_AGG'].fillna(df_tmp['TARGET_AGG'].mean(), inplace=True)

df_tmp.apply(lambda x: sum(x.isnull()), axis=0)

# df_tmp

In [ ]:
df['CENTER'].unique()

## Business Growth

In [3]:
# df_bg = df[(df['CENTER'] == 'Sales & Revenue') & (df['BG_FLAG'] == 'Y')]
df_bg = df[(df['BG_FLAG'] == 'Y') | ('METRIC_NAME' == 'TDG Revenue (Performance View)')]
df_bg.head()

,TM_KEY_MTH,TM_KEY_WK,CENTER,METRIC_GRP,COMP_CD,PRODUCT_GRP,METRIC_CD,METRIC_NAME,DIMENSION_KPI_FLAG,BG_FLAG,AGG_TYPE,RR_IND,GRY_IND,UOM,PERIOD,ACTUAL_AGG,TARGET_AGG,PPN_TM
133,202303,2023009,New S-Curve,Revenue,TRUE,TDG,TNSC00142,TDG Revenue (Performance View),Y,Y,N,0,GYR,baht,M,NaN,NaN,2023-05-22 17:50:18
137,202303,2023009,Sales & Revenue,Revenue,ALL,Postpaid,B2R000100,Postpaid Revenue,Y,Y,S,0,GYR,baht,M,1.157226e+09,1.165612e+09,2023-05-22 17:50:18
165,202303,2023009,Sales & Revenue,Revenue,ALL,Prepaid,B1R000100,Prepaid Revenue,Y,Y,S,1,GYR,baht,M,6.699010e+08,6.262193e+08,2023-05-22 17:50:18
286,202303,2023009,Sales & Revenue,Revenue,TRUE,TOL,TB3R000100,TOL Revenue,Y,Y,S,0,GYR,baht,M,1.897132e+08,2.051734e+08,2023-05-22 17:50:18
292,202303,2023009,Sales & Revenue,Revenue,TRUE,TVS,TB4R000100,TVS Revenue,Y,Y,S,0,GYR,baht,M,4.243065e+07,4.755595e+07,2023-05-22 17:50:18

In [ ]:
df_bg.describe()

In [ ]:
df_bg.shape

In [ ]:
# df_bg.sort_values(by=['TM_KEY_MTH', 'TM_KEY_WK', 'CENTER', 'METRIC_GRP', 'COMP_CD', 'PRODUCT_GRP', 'METRIC_CD'], ascending=True)
# df_bg.head()

## Monthly Aggregate

In [ ]:
# df_bg_agg_1 = pd.DataFrame(df_bg.groupby(['TM_KEY_MTH', 'TM_KEY_WK', 'METRIC_CD', 'METRIC_NAME'])['ACTUAL_AGG'].sum().reset_index())
# df_bg_agg_1

# df_bg_agg_2 = pd.DataFrame(df_bg.groupby(['TM_KEY_MTH', 'TM_KEY_WK', 'METRIC_CD', 'METRIC_NAME'])['ACTUAL_AGG'].agg(['sum', 'count']).reset_index())
# df_bg_agg_2

# df_bg_agg = pd.DataFrame(df_bg.groupby(['TM_KEY_MTH', 'TM_KEY_WK', 'METRIC_CD', 'METRIC_NAME']).agg({'ACTUAL_AGG': 'sum', 'TARGET_AGG': 'sum'}).reset_index())
# df_bg_agg['ACTUAL_AGG'] = df_bg_agg['ACTUAL_AGG'] / 1000000
# df_bg_agg['TARGET_AGG'] = df_bg_agg['TARGET_AGG'] / 1000000
# df_bg_agg.head()

In [ ]:
df_bg_agg_actual_mth = pd.DataFrame(df_bg.groupby(['TM_KEY_MTH', 'METRIC_CD', 'METRIC_NAME'])['ACTUAL_AGG'].sum().reset_index())
df_bg_agg_actual_mth.rename(columns={'ACTUAL_AGG': 'AGG'}, inplace=True)
df_bg_agg_actual_mth['MEASURE'] = 'ACTUAL'
df_bg_agg_actual_mth.head()

In [ ]:
df_bg_agg_target_mth = pd.DataFrame(df_bg.groupby(['TM_KEY_MTH', 'METRIC_CD', 'METRIC_NAME'])['TARGET_AGG'].sum().reset_index())
df_bg_agg_target_mth.rename(columns={'TARGET_AGG': 'AGG'}, inplace=True)
df_bg_agg_target_mth['MEASURE'] = 'TARGET'
df_bg_agg_target_mth.head()

In [ ]:
df_bg_agg_mth = pd.concat([df_bg_agg_actual_mth, df_bg_agg_target_mth])
df_bg_agg_mth['AGG'] = df_bg_agg_mth['AGG'] / 1000000
df_bg_agg_mth.head()

In [ ]:
df_bg_agg_mth_pivot = df_bg_agg_mth.pivot(index=['TM_KEY_MTH', 'MEASURE'], columns=['METRIC_CD', 'METRIC_NAME'], values='AGG')
df_bg_agg_mth_pivot

In [ ]:
df_bg_agg_mth_pivot.T

## Weekly Aggregate

In [4]:
df_bg_agg_actual_wk = pd.DataFrame(df_bg.groupby(['TM_KEY_WK', 'METRIC_CD', 'METRIC_NAME'])['ACTUAL_AGG'].sum().reset_index())
df_bg_agg_actual_wk.rename(columns={'ACTUAL_AGG': 'AGG'}, inplace=True)
df_bg_agg_actual_wk['MEASURE'] = 'ACTUAL'
df_bg_agg_actual_wk.head()

   TM_KEY_WK   METRIC_CD                     METRIC_NAME           AGG MEASURE
0    2023009   B1R000100                 Prepaid Revenue  6.699010e+08  ACTUAL
1    2023009   B2R000100                Postpaid Revenue  1.157226e+09  ACTUAL
2    2023009  TB3R000100                     TOL Revenue  1.897132e+08  ACTUAL
3    2023009  TB4R000100                     TVS Revenue  4.243065e+07  ACTUAL
4    2023009   TNSC00142  TDG Revenue (Performance View)  0.000000e+00  ACTUAL

In [5]:
df_bg_agg_target_wk = pd.DataFrame(df_bg.groupby(['TM_KEY_WK', 'METRIC_CD', 'METRIC_NAME'])['TARGET_AGG'].sum().reset_index())
df_bg_agg_target_wk.rename(columns={'TARGET_AGG': 'AGG'}, inplace=True)
df_bg_agg_target_wk['MEASURE'] = 'TARGET'
df_bg_agg_target_wk.head()

   TM_KEY_WK   METRIC_CD                     METRIC_NAME           AGG MEASURE
0    2023009   B1R000100                 Prepaid Revenue  6.262193e+08  TARGET
1    2023009   B2R000100                Postpaid Revenue  1.165612e+09  TARGET
2    2023009  TB3R000100                     TOL Revenue  2.051734e+08  TARGET
3    2023009  TB4R000100                     TVS Revenue  4.755595e+07  TARGET
4    2023009   TNSC00142  TDG Revenue (Performance View)  0.000000e+00  TARGET

In [6]:
df_bg_agg_wk = pd.concat([df_bg_agg_actual_wk, df_bg_agg_target_wk])
df_bg_agg_wk['AGG'] = df_bg_agg_wk['AGG'] / 1000000
df_bg_agg_wk.head()

   TM_KEY_WK   METRIC_CD                     METRIC_NAME          AGG MEASURE
0    2023009   B1R000100                 Prepaid Revenue   669.901008  ACTUAL
1    2023009   B2R000100                Postpaid Revenue  1157.226110  ACTUAL
2    2023009  TB3R000100                     TOL Revenue   189.713166  ACTUAL
3    2023009  TB4R000100                     TVS Revenue    42.430646  ACTUAL
4    2023009   TNSC00142  TDG Revenue (Performance View)     0.000000  ACTUAL

In [40]:
df_bg_agg_wk_pivot = df_bg_agg_wk.pivot(index=['TM_KEY_WK', 'MEASURE'], columns=['METRIC_CD', 'METRIC_NAME'], values='AGG')
df_bg_agg_wk_pivot

METRIC_CD               B1R000100        B2R000100   TB3R000100  TB4R000100
METRIC_NAME       Prepaid Revenue Postpaid Revenue  TOL Revenue TVS Revenue
TM_KEY_WK MEASURE
2023009   ACTUAL       669.901008      1157.226110   189.713166   42.430646  \
          TARGET       626.219335      1165.611851   205.173356   47.555946
2023010   ACTUAL      1489.022666      2542.704602   495.345550   90.125908
          TARGET      1464.916905      2560.219921   531.751420  100.809440
2023011   ACTUAL      2265.823689      4320.113830   952.874775  171.662212
          TARGET      2281.464179      4365.499251  1020.472959  191.372497
2023012   ACTUAL      3055.198017      5690.431029  1246.037826  223.404091
          TARGET      3090.841192      5739.945715  1332.357409  249.176747
2023013   ACTUAL      3957.430826      7480.288742  1594.478765  314.918953
          TARGET      3952.692098      7566.681744  1704.092759  461.172292
2023014   ACTUAL      1119.646034      1796.362050   297.357600   54.017140
          TARGET      1122.306286      1824.546824   315.377689   59.556469
2023015   ACTUAL      1915.320975      3738.327769   811.312854  147.393232
          TARGET      1966.023512      3742.821992   868.398705  163.256489
2023016   ACTUAL      2708.196763      5094.394930  1104.788064  199.085020
          TARGET      2791.999798      5104.686973  1183.863639  220.237468
2023017   ACTUAL      3584.677321      6654.114487  1405.515708  273.695322
          TARGET      3639.376740      6672.685694  1506.832153  413.616346
2023018   ACTUAL       881.977049      1598.840611   302.013865   32.424082
          TARGET       869.299484      1601.325381   317.296714   59.556469
2023019   ACTUAL      1696.805386      3148.724083   665.094200   64.693808
          TARGET      1696.016607      3154.018522   702.801628  131.083517
2023020   ACTUAL      2279.430558      4323.157480   970.832428   94.190016
          TARGET      2285.080635      4348.522851  1032.967830  191.372497

METRIC_CD                              TNSC00142
METRIC_NAME       TDG Revenue (Performance View)
TM_KEY_WK MEASURE
2023009   ACTUAL                        0.000000
          TARGET                        0.000000
2023010   ACTUAL                      572.769624
          TARGET                      522.000000
2023011   ACTUAL                      572.769624
          TARGET                      522.000000
2023012   ACTUAL                      572.769624
          TARGET                      522.000000
2023013   ACTUAL                      572.769624
          TARGET                      522.000000
2023014   ACTUAL                      564.000000
          TARGET                      535.000000
2023015   ACTUAL                      546.000000
          TARGET                      535.000000
2023016   ACTUAL                      539.000000
          TARGET                      535.000000
2023017   ACTUAL                      538.000000
          TARGET                      535.000000
2023018   ACTUAL                      561.000000
          TARGET                      503.000000
2023019   ACTUAL                      561.000000
          TARGET                      503.000000
2023020   ACTUAL                      561.000000
          TARGET                      503.000000

In [41]:
output_data = df_bg_agg_wk_pivot.T
output_data.round(2)

TM_KEY_WK                                  2023009           2023010
MEASURE                                     ACTUAL   TARGET   ACTUAL   TARGET
METRIC_CD  METRIC_NAME
B1R000100  Prepaid Revenue                  669.90   626.22  1489.02  1464.92  \
B2R000100  Postpaid Revenue                1157.23  1165.61  2542.70  2560.22
TB3R000100 TOL Revenue                      189.71   205.17   495.35   531.75
TB4R000100 TVS Revenue                       42.43    47.56    90.13   100.81
TNSC00142  TDG Revenue (Performance View)     0.00     0.00   572.77   522.00

TM_KEY_WK                                  2023011           2023012
MEASURE                                     ACTUAL   TARGET   ACTUAL   TARGET
METRIC_CD  METRIC_NAME
B1R000100  Prepaid Revenue                 2265.82  2281.46  3055.20  3090.84  \
B2R000100  Postpaid Revenue                4320.11  4365.50  5690.43  5739.95
TB3R000100 TOL Revenue                      952.87  1020.47  1246.04  1332.36
TB4R000100 TVS Revenue                      171.66   191.37   223.40   249.18
TNSC00142  TDG Revenue (Performance View)   572.77   522.00   572.77   522.00

TM_KEY_WK                                  2023013           ...  2023016
MEASURE                                     ACTUAL   TARGET  ...   ACTUAL
METRIC_CD  METRIC_NAME                                       ...
B1R000100  Prepaid Revenue                 3957.43  3952.69  ...  2708.20  \
B2R000100  Postpaid Revenue                7480.29  7566.68  ...  5094.39
TB3R000100 TOL Revenue                     1594.48  1704.09  ...  1104.79
TB4R000100 TVS Revenue                      314.92   461.17  ...   199.09
TNSC00142  TDG Revenue (Performance View)   572.77   522.00  ...   539.00

TM_KEY_WK                                           2023017           2023018
MEASURE                                     TARGET   ACTUAL   TARGET   ACTUAL
METRIC_CD  METRIC_NAME
B1R000100  Prepaid Revenue                 2792.00  3584.68  3639.38   881.98  \
B2R000100  Postpaid Revenue                5104.69  6654.11  6672.69  1598.84
TB3R000100 TOL Revenue                     1183.86  1405.52  1506.83   302.01
TB4R000100 TVS Revenue                      220.24   273.70   413.62    32.42
TNSC00142  TDG Revenue (Performance View)   535.00   538.00   535.00   561.00

TM_KEY_WK                                           2023019           2023020
MEASURE                                     TARGET   ACTUAL   TARGET   ACTUAL
METRIC_CD  METRIC_NAME
B1R000100  Prepaid Revenue                  869.30  1696.81  1696.02  2279.43  \
B2R000100  Postpaid Revenue                1601.33  3148.72  3154.02  4323.16
TB3R000100 TOL Revenue                      317.30   665.09   702.80   970.83
TB4R000100 TVS Revenue                       59.56    64.69   131.08    94.19
TNSC00142  TDG Revenue (Performance View)   503.00   561.00   503.00   561.00

TM_KEY_WK
MEASURE                                     TARGET
METRIC_CD  METRIC_NAME
B1R000100  Prepaid Revenue                 2285.08
B2R000100  Postpaid Revenue                4348.52
TB3R000100 TOL Revenue                     1032.97
TB4R000100 TVS Revenue                      191.37
TNSC00142  TDG Revenue (Performance View)   503.00

[5 rows x 24 columns]

## Generate Output File

In [ ]:
# output_data.to_csv("Agg Performance.csv")

In [42]:
# output_data.to_excel("Agg Performance.xlsx")